import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ThemeToggle } from "@/components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // `suppressHydrationWarning` only affects the html tag,
    // and is needed by `ThemeProvider` which sets the theme
    // class attribute on it
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ConvexClientProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            {" "}
            <div className="flex min-h-screen w-full flex-col">
              <main className="flex grow flex-col">
                <div className="mt-4">
                  <ThemeToggle />
                </div>
                {children}
              </main>
            </div>
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}

// function FooterLink({ href, children }: { href: string; children: ReactNode }) {
//   return (
//     <Link
//       href={href}
//       className="underline underline-offset-4 hover:no-underline"
//       target="_blank"
//     >
//       {children}
//     </Link>
//   );
// }

// function SplashPageNav() {
//   return (
//     <>
//       <Link
//         href="https://docs.convex.dev"
//         className="text-muted-foreground transition-colors hover:text-foreground"
//       >
//         Docs
//       </Link>
//       <Link
//         href="https://stack.convex.dev"
//         className="text-muted-foreground transition-colors hover:text-foreground"
//       >
//         Stack
//       </Link>
//       <Link
//         href="https://www.convex.dev/community"
//         className="text-muted-foreground transition-colors hover:text-foreground"
//       >
//         Discord
//       </Link>
//       <Link href="/product">
//         <Button>Get Started</Button>
//       </Link>
//     </>
//   );
// }
